Port to platformio
groundlight/esp32cam pull request #5
Opened 2023-06-13 00:01 UTC by max-at-groundlight

The `platformio.ini` file describes the board and the libraries, so deploying is quite trivial with the Platform IO extension. Readme is updated to be a little more verbose. Arduino IDE support is still present.

2023-06-13 17:00 UTC, positavi commented on edgelight/include/README
i don't think we need a readme for this.

2023-06-13 17:16 UTC, positavi commented on edgelight/lib/README
i don't think we need a readme here

2023-06-13 17:16 UTC, positavi commented on edgelight/src/.DS_Store
this shouldn't be in here.  its a private file from your laptop.

2023-06-13 17:17 UTC, positavi commented on edgelight/.gitignore
i don't think this is needed especially for hidden files.

2023-06-13 17:18 UTC, positavi commented on edgelight/.vscode/extensions.json
not needed.

2023-06-13 17:23 UTC, positavi requested changes
there are a bunch of files included here inadvertently that shouldn't be here, e.g. the .DS_Store files from your laptop.  

probably don't need the .gitignore for this or the .vscode.  you can update the main readme with the link the platformio install docs. 

i don't think you need readme files in all the subdirectories.  maybe those are default from platformIO setup ?  ideally eliminate the directories if there are no files in there anyway.   you could try eliminating them from the repo and seeing if platformio automatically creates them locally when opening the project, which is probably ideal. 

i would expect the only files in this repo are :

README.md
platformio.ini
edgelight.ino

2023-06-13 19:35 UTC, max-at-groundlight commented
@positavi

.vscode is automatically generated but the test, lib, and include directories are not. You are correct that those directories and their README files are generated when creating a new platform io project, but not when opening an existing one.

Also I believe that we should keep the generated .gitignore because it keeps git from including the .pio folder containing all of the build files and downloaded libraries.

Would you still like me to remove the directories and/or the .gitignore file?

2023-06-14 16:53 UTC, positavi requested changes
looks like there is still a .DS_Store file in the src directory to be removed.

agree to keep the .gitignore to keep from accidentally adding piles of files down the road.

maybe just trim the README to something very short saying this directory is part of the platformIO structure but not needed for this project .. i.e. justifying that it is otherwise empty.

2023-08-21 21:21 UTC, closed without merging